title: "Blog title"
author: "Funsuk Wangdu"
description: "Your amazing blog should have a sassy description"

# Jekyll settings
permalink: /:title:output_ext # see https://jekyllrb.com/docs/permalinks/
paginate: 2                   # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"   # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: true         # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: false            # enables dark mode
dark_header: true           # uses dark header whether dark_theme is enabled or not
minimal_theme: false         # radically minimalistic theme

navigation:                  # show navigation links in the header
  - index.html
  - archive.md
  - about.md


icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
  envelope: "mailto:<user@mailid.com>"
  github: "https://github.com/<username>/<repo>"
  rss: "/<repo>/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
